version: 2
jobs:
  build_and_deploy_to_gcr:
    docker:
     - image: google/cloud-sdk
    steps:
      - checkout
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - setup_remote_docker
      - deploy:
          name: Build and Push application Docker image
          command: |
            docker build -t app . 
            gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io
            docker tag app "${GCR_ENDPOINT}/donate-api:${CIRCLE_BRANCH}-${CIRCLE_SHA1}"
            docker push "${GCR_ENDPOINT}/donate-api:${CIRCLE_BRANCH}-${CIRCLE_SHA1}"
workflows:
    version: 2
    build-push:
        jobs:
          - build_and_deploy_to_gcr
